"""Conversation-agent guardrails -- code-side enforcement that mirrors the
per-tenant system prompt rules generated by the Builder (``builder/prompts.py``
``CONVERSATION_SYSTEM_TEMPLATE`` rules 1-6).

Per the skill invariant, guardrails live in BOTH places and must change
together: the prompt instructs the model, and these checks catch the cases it
slips through. Everything here is pure (no I/O, no LLM) so it is fully unit
testable without credentials.
"""

from __future__ import annotations

import re
from collections.abc import Iterable

# --------------------------------------------------------------------------- #
# Language mirroring (rule 4)
# --------------------------------------------------------------------------- #
_HEBREW_RE = re.compile(r"[֐-׿]")

# Emoji character classes -- strip_emojis() uses this as a mechanical backstop.
_EMOJI_RE = re.compile(
    "["
    "\U0001F000-\U0001FFFF"  # emoticons, misc symbols, pictographs, transport
    "\U00002600-\U000027FF"  # misc symbols (sun, heart, check mark, etc.)
    "\U00002B00-\U00002BFF"  # misc symbols and arrows (star, etc.)
    "\U0000FE00-\U0000FE0F"  # variation selectors (emoji modifiers)
    "\U0000200D"             # zero-width joiner (compound emoji)
    "]",
    re.UNICODE,
)


def detect_language(text: str) -> str:
    """Return ``"he"`` if the text contains Hebrew letters, else ``"en"``."""
    return "he" if _HEBREW_RE.search(text or "") else "en"


def language_directive(lang: str) -> str:
    if lang == "he":
        return "The customer wrote in Hebrew. Reply in Hebrew."
    return "The customer wrote in English. Reply in English."


# --------------------------------------------------------------------------- #
# Price/stock honesty (rules 2 & 3): never invent prices.
# Deliberately narrow -- only flag a number that sits next to a currency marker,
# so bare counts ("we have 3 sofas", "open until 18:00") are never blocked.
# --------------------------------------------------------------------------- #
_CURRENCY = r"(?:₪|ILS|NIS|shekels?|שקלים|שקל|ש\"ח)"
_NUM = r"\d{1,3}(?:[,\s]\d{3})+(?:\.\d+)?|\d+(?:\.\d+)?"
_AMOUNT_RE = re.compile(
    rf"{_CURRENCY}\s*({_NUM})|({_NUM})\s*{_CURRENCY}",
    re.IGNORECASE,
)


def _normalize_amount(raw: str) -> float | None:
    cleaned = raw.replace(",", "").replace(" ", "")
    try:
        return float(cleaned)
    except ValueError:
        return None


def extract_currency_amounts(text: str) -> list[float]:
    """Numbers in `text` that are adjacent to a currency marker."""
    out: list[float] = []
    for match in _AMOUNT_RE.finditer(text or ""):
        raw = match.group(1) or match.group(2)
        value = _normalize_amount(raw)
        if value is not None:
            out.append(value)
    return out


def any_price_mention(text: str) -> bool:
    """True when ``text`` contains any currency-adjacent number.

    Used for ``lead_qualification`` tenants where ALL price mentions are
    forbidden regardless of tool results.  Reuses ``extract_currency_amounts``
    so the detection logic stays in one place.
    """
    return bool(extract_currency_amounts(text))


def unsupported_price_claim(reply: str, allowed_prices: Iterable[float]) -> float | None:
    """First currency-adjacent amount in `reply` not backed by a tool-result
    price, or ``None`` when every such amount is supported (or there are none).
    """
    allowed = {round(float(p), 2) for p in allowed_prices if p is not None}
    for amount in extract_currency_amounts(reply):
        if round(amount, 2) not in allowed:
            return amount
    return None


# --------------------------------------------------------------------------- #
# Handoff triggers (rule 5): anger or an explicit request for a human.
# --------------------------------------------------------------------------- #
_HUMAN_RE = re.compile(
    r"\b(human|real person|speak to (?:someone|a person|an agent)|"
    r"talk to (?:someone|a person|an agent)|representative|manager|customer service)\b"
    r"|נציג(?:ה)?|אנושי|בן[ -]?אדם|לדבר עם מישהו|נציג שירות",
    re.IGNORECASE,
)
_ANGER_RE = re.compile(
    r"\b(angry|furious|useless|terrible|ridiculous|scam|fed up|stupid|worst|"
    r"unacceptable|disgrace)\b"
    r"|זבל|נורא|גרוע|מעצבן|נמאס|שערורי|לא מקובל",
    re.IGNORECASE,
)


def wants_human(text: str) -> bool:
    return bool(_HUMAN_RE.search(text or ""))


def is_angry(text: str) -> bool:
    return bool(_ANGER_RE.search(text or ""))


def should_handoff(text: str) -> bool:
    """True when the customer is angry or explicitly asks for a human (rule 5)."""
    return wants_human(text) or is_angry(text)


# --------------------------------------------------------------------------- #
# System-prompt reinforcement (mirrors builder/prompts.py rules 1-6).
# Appended to the tenant's generated system_prompt at runtime, alongside the
# per-turn language directive and current time.
# --------------------------------------------------------------------------- #
RUNTIME_GUARDRAILS = (
    "Operating rules (enforced):\n"
    "1. Only discuss THIS business's catalog and information. Politely decline anything"
    " else and offer to connect a human.\n"
    "2. Never invent or estimate a price or stock status. Prices and availability must"
    " come from your tool results. Never quote a price recalled from earlier in the"
    " conversation -- call search_products again this turn to re-confirm it first,"
    ' even for follow-ups like "how much is the white one?".\n'
    "3. When a product is out of stock, say so clearly. Never imply availability you"
    " have not confirmed via a tool.\n"
    "4. Mirror the customer's language: Hebrew in → Hebrew out, English in → English out.\n"
    "5. If the customer is angry or asks for a human, call handoff_to_human.\n"
    "6. Never reveal that you serve other businesses or that you are an AI platform/model.\n"
    "7. Reply in plain WhatsApp text only. Never use markdown, asterisks, bold, or"
    " bullet formatting. Write product names and prices as plain text.\n"
    '8. When the customer asks for a price range, answer with the lowest and highest'
    ' prices among the retrieved products. When asked which product is "best" or for a'
    " recommendation, pick a suitable product from the retrieved results and give a"
    " one-line reason -- don't decline.\n"
    "9. If a requested product has no price available, do not state a price; acknowledge"
    " it and offer a similar in-catalog product instead.\n"
    "10. If a requested product is out of stock, say so clearly and suggest a similar"
    " available product from the catalog.\n"
    "11. If you do not understand the customer's question, ask them to rephrase or"
    " clarify rather than guessing or giving a poor answer.\n"
    "\n"
    "Tools: use search_products to find products; get_business_info for"
    " hours/location/policies; send_product_cards to show a customer specific products"
    " (photo, name, price); handoff_to_human to escalate."
)


# --------------------------------------------------------------------------- #
# Voice / tone. Tenant-agnostic, so it lives here (applied to every turn via
# system_preamble) rather than in each tenant's generated system_prompt --
# iterating on tone must not require rebuilding every tenant. Not a guardrail:
# no invariant-#8 mirror obligation.
# --------------------------------------------------------------------------- #
RUNTIME_VOICE = (
    "VOICE -- sound like a real person on WhatsApp:\n"
    "- Warm, friendly, and concise. Keep it short, like texting -- usually 1-3 sentences.\n"
    '- Conversational, not corporate. Skip formal openings ("Dear customer") and robotic'
    ' phrasing ("I am unable to assist with that request"). Talk like a helpful shop'
    " assistant who knows the products.\n"
    "- Mirror the customer's register, not just their language: casual gets casual,"
    " formal gets a touch more formal.\n"
    "- Hebrew must read as natural, idiomatic Hebrew -- the way an Israeli salesperson"
    " actually writes on WhatsApp -- never stiff or translated-sounding. Everyday"
    " phrasing over formal constructions.\n"
    "- A single well-placed emoji is fine when it fits; don't overdo it. Lead with the"
    " useful answer, pleasantries second.\n"
    "- When a customer asks about a specific product or its price, state the key fact --"
    " the product name and price (and stock, if relevant) -- in your TEXT reply, even"
    " when you also send a card. The card supports the message; it never replaces the answer.\n"
    "- When you show product cards, always write a short line of text with them -- never"
    " end your reply with only cards and no words.\n"
    "- When you don't know something, say so plainly and offer the next step (search,"
    " business info, or a human) -- don't apologize repeatedly."
)


# --------------------------------------------------------------------------- #
# Lead-qualification guardrails (mirrors LEAD_QUALIFICATION_TEMPLATE rules).
# Applied per-turn when agent_type == "lead_qualification".
# Invariant #8: both prompt template and this code block must be updated
# together when the no-price rule changes.
# --------------------------------------------------------------------------- #
RUNTIME_GUARDRAILS_LEADQUAL = (
    "Operating rules (enforced):\n"
    "1. NEVER discuss prices, packages, fees, payment plans, durations, session counts,"
    " or any commercial terms. When asked, deflect with: 'The trainer builds you a"
    " personal plan toward your goals and goes over everything with you personally.'"
    " Never say 'prices are personalized' -- frame around the trainer's personalised"
    " plan. Never invent a number.\n"
    "2. Mirror the customer's language: Hebrew in → Hebrew out, English in → English out.\n"
    "3. If the customer is angry or asks for a human, call handoff_to_human immediately.\n"
    "4. Never reveal that you are an AI, that you serve other businesses, or name any"
    " AI platform or model.\n"
    "5. Reply in plain WhatsApp text only. No markdown, asterisks, bold, or bullet"
    " formatting.\n"
    "6. Keep replies warm and conversational -- typically 2-3 sentences, enough to"
    " actually answer and build a little rapport. Not terse one-liners.\n"
    "7. If you do not understand the customer's question, ask them to rephrase or"
    " clarify.\n"
    "8. Your only tool is handoff_to_human. Do not search products or retrieve catalog"
    " info.\n"
    "9. Answer informational questions directly from the business information in the"
    " system prompt. Do NOT call handoff_to_human for questions you can answer (what"
    " the service is, how it works, what to bring, hours, location, suitability). Call"
    " handoff_to_human ONLY for: price/package/payment questions, medical conditions or"
    " physical limitations, booking a specific session time, cancellations, or questions"
    " not covered in the business information.\n"
    "10. Never assert medical safety, clearance, or prohibition. If the customer mentions"
    " any medical condition, physical limitation, injury, or health concern, respond"
    " warmly: if the message also contains an answerable question, answer that part"
    " first; then acknowledge that the trainer works with all kinds of conditions and"
    " tailors every programme personally, then call handoff_to_human. Never say"
    " 'I don't know' or 'consult a doctor' -- always hand off to the trainer."
    " Never make or imply a medical judgement.\n"
    "11. The customer's phone number is already known from WhatsApp -- never ask for a"
    " phone number. At handoff you may only confirm: 'The trainer will call you back"
    " on this number?' Never request it fresh.\n"
    "12. If the customer has mentioned their name during the conversation, use it and"
    " do not ask again. Ask for a name (once, gently, before handoff) only if you"
    " genuinely do not have one.\n"
    "13. Vary your message endings. Never repeat the same closing structure twice in a"
    " row. Rotate across forms: sometimes a question ('What is your goal?'),"
    " sometimes a forward statement ('David will get back to you'), sometimes no"
    " explicit closer at all when the exchange speaks for itself.\n"
    "\n"
    "Tools available: handoff_to_human -- call ONLY when: the person is ready for next"
    " steps, is angry, asks for a person, mentions any medical or physical health"
    " concern, asks about price/packages, or requests a specific booking. Do NOT call"
    " it for informational questions the business information covers."
)


def system_preamble(lang: str, now_str: str, agent_type: str = "catalog_sales") -> str:
    """Runtime guardrail + voice block appended to the tenant system prompt each turn.

    ``agent_type`` selects the guardrail block:
    - ``"lead_qualification"``: no-price + handoff-only rules.
    - anything else (default ``"catalog_sales"``): full catalog/price rules.
    """
    guardrail_block = (
        RUNTIME_GUARDRAILS_LEADQUAL
        if agent_type == "lead_qualification"
        else RUNTIME_GUARDRAILS
    )
    emoji_override = (
        "\n\nNo emojis -- never include any emoji character in a lead-qualification reply."
        if agent_type == "lead_qualification"
        else ""
    )
    return (
        f"{guardrail_block}\n\n{RUNTIME_VOICE}{emoji_override}\n\n"
        f"{language_directive(lang)}\nCurrent date and time: {now_str}."
    )


def fallback_reply(lang: str) -> str:
    """Graceful, language-mirrored reply for max-iteration / empty-response cases."""
    if lang == "he":
        return (
            "סליחה, לא הצלחתי"
            " להשלים את התשובה"
            " כרגע. אפשר לנסח"
            " מחדש, או שאחבר"
            " אותך לנציג אנושי?"
        )
    return (
        "Sorry, I couldn't complete that just now. Could you rephrase, "
        "or I can connect you with a human?"
    )


def strip_emojis(text: str) -> str:
    """Remove all emoji characters from *text*.

    Applied to lead_qualification replies as a mechanical backstop after the
    LLM call -- the system prompt already instructs no emojis; this ensures
    none slip through regardless.
    """
    return _EMOJI_RE.sub("", text)



def _format_price(price: float, currency: str | None) -> str:
    """₪3,990 for ILS, else '3,990 ILS'. Comma thousands; drop a .0 tail."""
    n = int(price) if float(price).is_integer() else price
    amount = f"{n:,}"
    cur = (currency or "").upper()
    return f"₪{amount}" if cur in ("ILS", "NIS") else f"{amount} {cur}".strip()


def cards_only_reply(lang: str, cards) -> str:
    """Neutral line when the agent sent product cards but no text of its own -- the
    turn succeeded, so don't fire the apologetic fallback after a card. Carries the
    card's name + price so the answer is never missing even on a silent turn."""
    parts = []
    for c in cards[:3]:
        name = ((c.name_he if lang == "he" else c.name_en) or c.name_en or c.name_he or "").strip()
        if name and c.price is not None:
            parts.append(f"{name} — {_format_price(c.price, c.currency)}")
        elif name:
            parts.append(name)
    listing = "; ".join(parts)
    if not listing:
        return (
            "הנה מה שמצאתי \U0001f642"
            " אפשר לעזור בעוד משהו?"
            if lang == "he"
            else "Here's what I found \U0001f642 Anything else I can help with?"
        )
    if lang == "he":
        return (
            f"{listing}. רוצה עוד פרטים?"
        )
    return f"{listing}. Want more details?"
