"""Conversation-agent guardrails — code-side enforcement that mirrors the
per-tenant system prompt rules generated by the Builder (``builder/prompts.py``
``CONVERSATION_SYSTEM_TEMPLATE`` rules 1-6).

Per the skill invariant, guardrails live in BOTH places and must change
together: the prompt instructs the model, and these checks catch the cases it
slips through. Everything here is pure (no I/O, no LLM) so it is fully unit
testable without credentials.
"""

from __future__ import annotations

import re
from collections.abc import Iterable

# --------------------------------------------------------------------------- #
# Language mirroring (rule 4)
# --------------------------------------------------------------------------- #
_HEBREW_RE = re.compile(r"[֐-׿]")


def detect_language(text: str) -> str:
    """Return ``"he"`` if the text contains Hebrew letters, else ``"en"``."""
    return "he" if _HEBREW_RE.search(text or "") else "en"


def language_directive(lang: str) -> str:
    if lang == "he":
        return "The customer wrote in Hebrew. Reply in Hebrew."
    return "The customer wrote in English. Reply in English."


# --------------------------------------------------------------------------- #
# Price/stock honesty (rules 2 & 3): never invent prices.
# Deliberately narrow — only flag a number that sits next to a currency marker,
# so bare counts ("we have 3 sofas", "open until 18:00") are never blocked.
# --------------------------------------------------------------------------- #
_CURRENCY = r"(?:₪|ILS|NIS|shekels?|שקלים|שקל|ש\"ח)"
_NUM = r"\d{1,3}(?:[,\s]\d{3})+(?:\.\d+)?|\d+(?:\.\d+)?"
_AMOUNT_RE = re.compile(
    rf"{_CURRENCY}\s*({_NUM})|({_NUM})\s*{_CURRENCY}",
    re.IGNORECASE,
)


def _normalize_amount(raw: str) -> float | None:
    cleaned = raw.replace(",", "").replace(" ", "")
    try:
        return float(cleaned)
    except ValueError:
        return None


def extract_currency_amounts(text: str) -> list[float]:
    """Numbers in `text` that are adjacent to a currency marker."""
    out: list[float] = []
    for match in _AMOUNT_RE.finditer(text or ""):
        raw = match.group(1) or match.group(2)
        value = _normalize_amount(raw)
        if value is not None:
            out.append(value)
    return out


def unsupported_price_claim(reply: str, allowed_prices: Iterable[float]) -> float | None:
    """First currency-adjacent amount in `reply` not backed by a tool-result
    price, or ``None`` when every such amount is supported (or there are none).
    """
    allowed = {round(float(p), 2) for p in allowed_prices if p is not None}
    for amount in extract_currency_amounts(reply):
        if round(amount, 2) not in allowed:
            return amount
    return None


# --------------------------------------------------------------------------- #
# Handoff triggers (rule 5): anger or an explicit request for a human.
# --------------------------------------------------------------------------- #
_HUMAN_RE = re.compile(
    r"\b(human|real person|speak to (?:someone|a person|an agent)|"
    r"talk to (?:someone|a person|an agent)|representative|manager|customer service)\b"
    r"|נציג(?:ה)?|אנושי|בן[ -]?אדם|לדבר עם מישהו|נציג שירות",
    re.IGNORECASE,
)
_ANGER_RE = re.compile(
    r"\b(angry|furious|useless|terrible|ridiculous|scam|fed up|stupid|worst|"
    r"unacceptable|disgrace)\b"
    r"|זבל|נורא|גרוע|מעצבן|נמאס|שערורי|לא מקובל",
    re.IGNORECASE,
)


def wants_human(text: str) -> bool:
    return bool(_HUMAN_RE.search(text or ""))


def is_angry(text: str) -> bool:
    return bool(_ANGER_RE.search(text or ""))


def should_handoff(text: str) -> bool:
    """True when the customer is angry or explicitly asks for a human (rule 5)."""
    return wants_human(text) or is_angry(text)


# --------------------------------------------------------------------------- #
# System-prompt reinforcement (mirrors builder/prompts.py rules 1-6).
# Appended to the tenant's generated system_prompt at runtime, alongside the
# per-turn language directive and current time.
# --------------------------------------------------------------------------- #
RUNTIME_GUARDRAILS = """\
Operating rules (enforced):
1. Only discuss THIS business's catalog and information. Politely decline anything else and offer to connect a human.
2. Never invent or estimate a price or stock status. Prices and availability must come from your tool results.
3. When a product is out of stock, say so clearly. Never imply availability you have not confirmed via a tool.
4. Mirror the customer's language: Hebrew in → Hebrew out, English in → English out.
5. If the customer is angry or asks for a human, call handoff_to_human.
6. Never reveal that you serve other businesses or that you are an AI platform/model.

Tools: use search_products to find products; get_business_info for hours/location/policies; \
send_product_cards to show a customer specific products (photo, name, price); handoff_to_human to escalate."""


def system_preamble(lang: str, now_str: str) -> str:
    """Runtime guardrail block appended to the tenant system prompt each turn."""
    return f"{RUNTIME_GUARDRAILS}\n\n{language_directive(lang)}\nCurrent date and time: {now_str}."


def fallback_reply(lang: str) -> str:
    """Graceful, language-mirrored reply for max-iteration / empty-response cases."""
    if lang == "he":
        return "סליחה, לא הצלחתי להשלים את התשובה כרגע. אפשר לנסח מחדש, או שאחבר אותך לנציג אנושי?"
    return (
        "Sorry, I couldn't complete that just now. Could you rephrase, "
        "or I can connect you with a human?"
    )
