"""initial schema: 11 tables, halfvec(3072) + HNSW, GIN metadata, RLS

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-10

Authored by hand (not autogenerated): autogenerate misses the pgvector
extension, the halfvec column type + HNSW opclass, the GIN jsonb index, and
the Supabase RLS policies. Includes a guard that fails with a clear message if
the installed pgvector extension is older than 0.7.0 (halfvec was added in 0.7).
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from pgvector.sqlalchemy import HALFVEC

from alembic import op

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

EMBEDDING_DIM = 3072  # text-embedding-3-large native dims (registry: models.py)

# Tables carrying a direct tenant_id column — used to create their tenant_id
# btree index. (RLS is defined separately in _RLS_POLICIES below.)
_TENANT_TABLES = [
    "users",
    "whatsapp_instances",
    "agents",
    "products",
    "embeddings",
    "business_info",
    "conversations",
    "build_runs",
]

# The complete RLS surface: every row-protected table and its USING predicate,
# in one explicit, reviewable list. Anything NOT in this list (e.g. the
# alembic_version bookkeeping table) is intentionally left untouched by this
# migration. Direct-tenant tables filter on tenant_id; child tables isolate via
# their parent's tenant.
_TENANT_PREDICATE = "tenant_id IN (SELECT public.app_user_tenant_ids())"
_RLS_POLICIES: list[tuple[str, str]] = [
    ("tenants", "id IN (SELECT public.app_user_tenant_ids())"),
    ("users", _TENANT_PREDICATE),
    ("whatsapp_instances", _TENANT_PREDICATE),
    ("agents", _TENANT_PREDICATE),
    ("products", _TENANT_PREDICATE),
    ("embeddings", _TENANT_PREDICATE),
    ("business_info", _TENANT_PREDICATE),
    ("conversations", _TENANT_PREDICATE),
    ("build_runs", _TENANT_PREDICATE),
    (
        "product_images",
        "EXISTS (SELECT 1 FROM products p WHERE p.id = product_images.product_id "
        "AND p.tenant_id IN (SELECT public.app_user_tenant_ids()))",
    ),
    (
        "messages",
        "EXISTS (SELECT 1 FROM conversations c WHERE c.id = messages.conversation_id "
        "AND c.tenant_id IN (SELECT public.app_user_tenant_ids()))",
    ),
]


def _require_halfvec_support() -> None:
    """Fail loudly if pgvector is too old for halfvec (needs >= 0.7.0)."""
    bind = op.get_bind()
    version = bind.execute(
        sa.text("SELECT extversion FROM pg_extension WHERE extname = 'vector'")
    ).scalar()
    if version is None:
        raise RuntimeError(
            "pgvector extension is not installed after CREATE EXTENSION — "
            "cannot create halfvec columns."
        )
    try:
        parts = tuple(int(p) for p in version.split(".")[:3])
        parts = parts + (0,) * (3 - len(parts))
    except ValueError:  # pragma: no cover - unexpected version string
        raise RuntimeError(
            f"Could not parse pgvector version '{version}'. halfvec requires "
            "pgvector >= 0.7.0."
        )
    if parts < (0, 7, 0):
        raise RuntimeError(
            f"pgvector {version} is installed, but this schema uses halfvec(3072), "
            "which requires pgvector >= 0.7.0. Upgrade the extension "
            "(e.g. `ALTER EXTENSION vector UPDATE;` on a build with 0.7+ available, "
            "or upgrade your Postgres/pgvector image) and re-run the migration."
        )


def _timestamps() -> list[sa.Column]:
    return [
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    ]


def _id_col() -> sa.Column:
    return sa.Column(
        "id",
        sa.dialects.postgresql.UUID(as_uuid=False),
        primary_key=True,
        server_default=sa.text("gen_random_uuid()"),
    )


def _tenant_col() -> sa.Column:
    return sa.Column(
        "tenant_id",
        sa.dialects.postgresql.UUID(as_uuid=False),
        sa.ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
    )


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")  # gen_random_uuid()
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    _require_halfvec_support()

    pg = sa.dialects.postgresql

    # --- tenants ---
    op.create_table(
        "tenants",
        _id_col(),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("status", sa.String(32), nullable=False, server_default="active"),
        sa.Column("plan", sa.String(32), nullable=False, server_default="free"),
        *_timestamps(),
    )

    # --- users ---
    op.create_table(
        "users",
        _id_col(),
        _tenant_col(),
        sa.Column("supabase_user_id", pg.UUID(as_uuid=False), nullable=False, unique=True),
        sa.Column("email", sa.String(320), nullable=False),
        *_timestamps(),
    )

    # --- whatsapp_instances ---
    op.create_table(
        "whatsapp_instances",
        _id_col(),
        _tenant_col(),
        sa.Column("green_api_instance_id", sa.String(64), nullable=False),
        sa.Column("token_encrypted", sa.Text(), nullable=False),
        sa.Column("phone", sa.String(32)),
        sa.Column("status", sa.String(32), nullable=False, server_default="disconnected"),
        sa.Column("intake_mode", sa.String(16), nullable=False, server_default="polling"),
        *_timestamps(),
    )

    # --- agents ---
    op.create_table(
        "agents",
        _id_col(),
        _tenant_col(),
        sa.Column("system_prompt", sa.Text()),
        sa.Column("tone", sa.String(64)),
        sa.Column("language_policy", sa.String(64)),
        sa.Column("rules", pg.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("escalation", pg.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("status", sa.String(16), nullable=False, server_default="building"),
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
        *_timestamps(),
    )

    # --- products ---
    op.create_table(
        "products",
        _id_col(),
        _tenant_col(),
        sa.Column("stable_key", sa.String(255), nullable=False),
        sa.Column("name_he", sa.String(512)),
        sa.Column("name_en", sa.String(512)),
        sa.Column("description_he", sa.Text()),
        sa.Column("description_en", sa.Text()),
        sa.Column("category", sa.String(128)),
        sa.Column("attributes", pg.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("price", sa.Numeric(12, 2)),
        sa.Column("currency", sa.String(3), nullable=False, server_default="ILS"),
        sa.Column("in_stock", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("source", sa.String(32), nullable=False, server_default="owner_input"),
        *_timestamps(),
    )
    op.create_index(
        "uq_products_tenant_stable_key",
        "products",
        ["tenant_id", "stable_key"],
        unique=True,
    )

    # --- product_images ---
    op.create_table(
        "product_images",
        _id_col(),
        sa.Column(
            "product_id",
            pg.UUID(as_uuid=False),
            sa.ForeignKey("products.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("public_url", sa.Text()),
        sa.Column("caption_he", sa.Text()),
        sa.Column("caption_en", sa.Text()),
        *_timestamps(),
    )
    op.create_index("ix_product_images_product_id", "product_images", ["product_id"])

    # --- embeddings ---
    op.create_table(
        "embeddings",
        _id_col(),
        _tenant_col(),
        sa.Column("ref_type", sa.String(32), nullable=False),
        sa.Column("ref_id", pg.UUID(as_uuid=False), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("vector", HALFVEC(EMBEDDING_DIM), nullable=False),
        sa.Column("metadata", pg.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("status", sa.String(16), nullable=False, server_default="active"),
        *_timestamps(),
    )
    # ANN index over half-precision vectors (cosine). Buildable at 3072 dims
    # because halfvec lifts the 2000-dim HNSW cap that the `vector` type has.
    op.execute(
        "CREATE INDEX ix_embeddings_vector_hnsw ON embeddings "
        "USING hnsw (vector halfvec_cosine_ops)"
    )
    # Hybrid-filter payload.
    op.execute(
        "CREATE INDEX ix_embeddings_metadata_gin ON embeddings "
        "USING gin (metadata jsonb_path_ops)"
    )

    # --- business_info ---
    op.create_table(
        "business_info",
        _id_col(),
        _tenant_col(),
        sa.Column("topic", sa.String(32), nullable=False),
        sa.Column("content_he", sa.Text()),
        sa.Column("content_en", sa.Text()),
        *_timestamps(),
    )

    # --- conversations ---
    op.create_table(
        "conversations",
        _id_col(),
        _tenant_col(),
        sa.Column("customer_phone", sa.String(32), nullable=False),
        sa.Column("status", sa.String(32), nullable=False, server_default="open"),
        sa.Column("last_message_at", sa.DateTime(timezone=True)),
        *_timestamps(),
    )
    op.create_index(
        "ix_conversations_tenant_phone", "conversations", ["tenant_id", "customer_phone"]
    )

    # --- messages ---
    op.create_table(
        "messages",
        _id_col(),
        sa.Column(
            "conversation_id",
            pg.UUID(as_uuid=False),
            sa.ForeignKey("conversations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("direction", sa.String(16), nullable=False),
        sa.Column("type", sa.String(16), nullable=False, server_default="text"),
        sa.Column("content", sa.Text()),
        sa.Column("media_url", sa.Text()),
        sa.Column("agent_trace_id", sa.String(128)),
        *_timestamps(),
    )
    op.create_index("ix_messages_conversation_id", "messages", ["conversation_id"])

    # --- build_runs ---
    op.create_table(
        "build_runs",
        _id_col(),
        _tenant_col(),
        sa.Column("status", sa.String(16), nullable=False, server_default="running"),
        sa.Column("input_manifest", pg.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("report", pg.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("error", sa.Text()),
        sa.Column("started_at", sa.DateTime(timezone=True)),
        sa.Column("finished_at", sa.DateTime(timezone=True)),
        *_timestamps(),
    )

    # tenant_id indexes for every tenant-scoped table.
    for tbl in _TENANT_TABLES:
        op.create_index(f"ix_{tbl}_tenant_id", tbl, ["tenant_id"])

    _create_rls()


def _create_rls() -> None:
    """Supabase RLS: tenant isolation for the frontend (anon key).

    The backend uses the service role and bypasses RLS entirely; these policies
    constrain the browser client so a logged-in owner only ever sees their own
    tenant's rows. Maps auth.uid() -> tenant_id via the users table.
    """
    op.execute(
        """
        CREATE OR REPLACE FUNCTION public.app_user_tenant_ids()
        RETURNS SETOF uuid
        LANGUAGE sql STABLE SECURITY DEFINER
        SET search_path = public
        AS $$
            SELECT tenant_id FROM public.users WHERE supabase_user_id = auth.uid();
        $$;
        """
    )

    # Enable RLS + tenant-isolation policy on exactly the tables in _RLS_POLICIES.
    for tbl, using in _RLS_POLICIES:
        op.execute(f"ALTER TABLE {tbl} ENABLE ROW LEVEL SECURITY")
        op.execute(f"CREATE POLICY tenant_isolation ON {tbl} USING ({using})")


def downgrade() -> None:
    for tbl in [
        "build_runs",
        "messages",
        "conversations",
        "business_info",
        "embeddings",
        "product_images",
        "products",
        "agents",
        "whatsapp_instances",
        "users",
        "tenants",
    ]:
        op.drop_table(tbl)
    op.execute("DROP FUNCTION IF EXISTS public.app_user_tenant_ids()")
